### ISSUE TITLE
Certificate used for mocks is expired

### ISSUE THREAD

**Issue by mirekkukla** [mocko-app/mocko#107]
Hey there, it looks like the certificate for the "mockoapp.net" domain expired on May 1st 2024 (one day ago).

<img width="1146" alt="image" src="https://github.com/mocko-app/mocko/assets/903370/ccff56c3-6d8e-40dc-a28b-0b992fa97460">

(It's worth noting that the certificate for the "mocko.dev" domain remains valid for a few more months, ie the above only affects making mock requests).

Perhaps there was some problem with automated certificate renewal?

**Comment by gabriel-pinheiro** [comment]
Hey @mirekkukla ! Thanks for the report, I'm taking a look into it

**Comment by gabriel-pinheiro** [comment]
@mirekkukla we're back online! 😄 

I'm so sorry for the unavailability, the auto-renewal failed and no alerts were triggered.. I started the job manually but I'll take a look at what caused the issue.

Let me know if it worked!

**Comment by mirekkukla** [comment]
Good to go, thanks for the quick fix!
