### ISSUE TITLE
Ignore files and directories starting with dot

### ISSUE THREAD

**Issue by gabriel-pinheiro** [mocko-app/mocko#53]
Mocks from directories or files with names starting in `.` (dot) must not be loaded.

Get started with Mocko here:
https://mocko.dev/getting-started/standalone/

Run it locally following these instructions:
https://github.com/gabriel-pinheiro/mocko/blob/master/CONTRIBUTING.md

For this issue, you might want to change this method to ignore files and folders starting with `.`:
https://github.com/mocko-app/mocko/blob/master/mocko-proxy/src/definitions/definition.provider.ts#L87-L120

**Comment by chincholikarsalil** [comment]
The easiest thing that comes to my mind is adding an extra condition in `files.filter()` 

```
const mockFiles = files
    .filter(f => !f.isDir && !f.name.startsWith("."))
    .filter(f => f.name.endsWith(HCL_EXTENSION));

const subDirContents = (await Promise.all(files
    .filter(f => f.isDir && !f.name.startsWith("."))
    .map(f => this.getMockFilesContent(join(path, f.name)))))
        .flat();
```

Is there any way we can put a check on readdir itself?

**Comment by gabriel-pinheiro** [comment]
`Is there any way we can put a check on readdir itself?`
I don't think so, your solution seems good for me! Would you like to take this issue?

**Comment by chincholikarsalil** [comment]
> Would you like to take this issue?

Absolutely, but it seems I am a bit late on this one!
Anyway, thank you!
Cheers!
