### ISSUE TITLE
allow sharing mocks

### ISSUE THREAD

**Issue by paulius-valiunas** [mocko-app/mocko#93]
right now mocko.dev only allows creating a new mock or selecting an existing mock on your own account. It would be nice if it allowed me to invite other people to use and edit my mocks.

**Comment by gabriel-pinheiro** [comment]
Thank you for the suggestion! Sharing projects is planned to be released soon in the SaaS version :)
I'll let you know when its ready!

**Comment by gabriel-pinheiro** [comment]
Hey @paulius-valiunas !
A beta version of this feature has been release in production! I hope it helps 😄

**Comment by paulius-valiunas** [comment]
oh, that was fast :o Thank you!
